### ISSUE TITLE
When uploading to *.app, ask for confirmation iff folder name does not equal instance name

### ISSUE THREAD

**Issue by alxndrsn** [alxndrsn/medic-configurer#9]
folder: `.../standard`
instance: `standard.app...`
confirm: no

folder: `.../abc-denmark`
instance: `def-norway.app...`
confirm: yes

Example confirmation:

> `Are you sure you want to upload abc-denmark configuration to def-norway.app.medicmobile.org?`

And add colours around the config and instance names.

**Comment by abbyad** [comment]
Some results to fix from acceptance testing:
- [ ] Confirmation was shown even though folder name matched instance
- [ ] Confirmation was shown even though action did not get or put data to instance (optional)
- [ ] Color codes were displayed instead of actually coloring text
- [ ] Password in instance URL is echoed back to user (false password used in screenshot below)

![image](https://user-images.githubusercontent.com/789512/28578121-bbe18976-7126-11e7-889e-bff8970bf2f5.png)

**Comment by alxndrsn** [comment]
> Confirmation was shown even though action did not get or put data to instance (optional)

Won't be fixing this for now.

**Comment by abbyad** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/789512/28579514-e60263de-712a-11e7-91a5-62e06af5276f.png)
